CREATE DATABASE IF NOT EXISTS conferenceqr CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE conferenceqr;
CREATE TABLE IF NOT EXISTS attendees (id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS places (id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(10) UNIQUE NOT NULL,name VARCHAR(255) NOT NULL,type ENUM('exhibitor','session') NOT NULL);
CREATE TABLE IF NOT EXISTS scans (id INT AUTO_INCREMENT PRIMARY KEY,attendee_id INT NOT NULL,place_id INT NOT NULL,scanned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(attendee_id,place_id),FOREIGN KEY(attendee_id) REFERENCES attendees(id),FOREIGN KEY(place_id) REFERENCES places(id));
