INSERT INTO places (code,name,type) VALUES ('S01','Presidential Symposium','session');
INSERT INTO places (code,name,type) VALUES ('S02','General Assembly','session');
INSERT INTO places (code,name,type) VALUES ('S03','Awards Ceremony','session');
INSERT INTO places (code,name,type) VALUES ('E01','Belluci Lab - Creighton University','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E02','Hyperacusis Research, Limited','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E03','Interacoustics','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E04','Turner Scientific','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E05','Royal National Institute for Deaf People','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E06','Intelligent Hearing Systems','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E07','Cortech Solutions Inc.','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E08','NIRx Medical Technologies, LLC','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E09','Sutter Instrument','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E10','Regeneron','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E11','Giant Tek, Inc.','exhibitor');
INSERT INTO places (code,name,type) VALUES ('E12','gene Expression Analysis Portal (gEAR)','exhibitor');